### ISSUE TITLE
Local field 'last_updated' in class 'Book' clashes with field of the same name from base class 'Post'.

### ISSUE THREAD

**Issue by dgleba** [mmcardle/django_builder#106]
I created a project from scratch.
I added Post model manually without using upload.
I added Book model with Post as parent.

I think the picture below shows the relevant info.

I get this error when running the project. What am I doing wrong? I think I just used the builder as you provide it.

```
djdev_1     | Watching for file changes with StatReloader
djdev_1     | Exception in thread django-main-thread:
djdev_1     | Traceback (most recent call last):
djdev_1     |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
djdev_1     |     self.run()
djdev_1     |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
djdev_1     |     self._target(*self._args, **self._kwargs)
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
djdev_1     |     fn(*args, **kwargs)
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
djdev_1     |     autoreload.raise_last_exception()
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
djdev_1     |     raise _exception[1]
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
djdev_1     |     autoreload.check_errors(django.setup)()
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
djdev_1     |     fn(*args, **kwargs)
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
djdev_1     |     apps.populate(settings.INSTALLED_APPS)
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
djdev_1     |     app_config.import_models()
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
djdev_1     |     self.models_module = import_module(models_module_name)
djdev_1     |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
djdev_1     |     return _bootstrap._gcd_import(name[level:], package, level)
djdev_1     |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
djdev_1     |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
djdev_1     |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
djdev_1     |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
djdev_1     |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
djdev_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
djdev_1     |   File "/code/blogapp/models.py", line 26, in <module>
djdev_1     |     class Book(Post):
djdev_1     |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 225, in __new__
djdev_1     |     base.__name__,
djdev_1     | django.core.exceptions.FieldError: Local field 'last_updated' in class 'Book' clashes with field of the same name from base class 'Post'.
djdev_1     |
```

![image](https://user-images.githubusercontent.com/4622715/95018056-0ad4a300-062b-11eb-835c-026dcce5a5f0.png)

**Comment by dgleba** [comment]
I used parent.
I removed that.

I have added a relationship - Foreign key - after creating both models.

**Comment by mmcardle** [comment]
Hi @dgleba 
Yes the relationships and structure of your models is up to you.
In Django you cannot have a field in a parent model that clashes with the field in the child model.
DjangoBuilder automatically adds `last_updated` and `created` for convenience, these can be deleted as required.

But in you case I think you want a relationship as you say.
